### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by DenizYil** [DenizYil/BDSA-Big-Hero-6#65]
- [x] Fix project updating (including leave, join, tags updates)
- [x] Front end for desktop
- [x] Fix trying to render before auth has been registered
- [x] Update tests for controllers so we still have ~100 coverage
- [x] Profile pictures
- [x] Figure out how to become a supervisor
- [x] Fix my projects not showing tags
- [x] Add copy to clipboard option for email
- [x] Add log out button
- [x] Add Integrations tests
